version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      kotlin-compose:
        patterns:
          - org.jetbrains.kotlin*
          - org.jetbrains.compose*
      androidx:
        patterns:
          - androidx.*
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ['*']
